In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library python digunakan untuk komputasi matriks. Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot. .....

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Rembang' 40.0 65000.0]
 ['Semarang' 37.0 54000.0]
 ['Kudus' 35.0 43000.0]
 ['Semarang' 26.0 76000.0]
 ['Kudus' 31.0 nan]
 ['Rembang' 28.0 83000.0]
 ['Semarang' nan 75000.0]
 ['Rembang' 34.0 49000.0]
 ['Kudus' 25.0 59000.0]
 ['Rembang' 41.0 67000.0]]


In [4]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Rembang' 40.0 65000.0]
 ['Semarang' 37.0 54000.0]
 ['Kudus' 35.0 43000.0]
 ['Semarang' 26.0 76000.0]
 ['Kudus' 31.0 63444.444444444445]
 ['Rembang' 28.0 83000.0]
 ['Semarang' 33.0 75000.0]
 ['Rembang' 34.0 49000.0]
 ['Kudus' 25.0 59000.0]
 ['Rembang' 41.0 67000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encorder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 40.0 65000.0]
 [0.0 0.0 1.0 37.0 54000.0]
 [1.0 0.0 0.0 35.0 43000.0]
 [0.0 0.0 1.0 26.0 76000.0]
 [1.0 0.0 0.0 31.0 63444.444444444445]
 [0.0 1.0 0.0 28.0 83000.0]
 [0.0 0.0 1.0 33.0 75000.0]
 [0.0 1.0 0.0 34.0 49000.0]
 [1.0 0.0 0.0 25.0 59000.0]
 [0.0 1.0 0.0 41.0 67000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[1 1 0 1 0 0 1 0 1 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 33.0 75000.0]
 [1.0 0.0 0.0 31.0 63444.444444444445]
 [0.0 1.0 0.0 40.0 65000.0]
 [0.0 0.0 1.0 26.0 76000.0]
 [0.0 0.0 1.0 37.0 54000.0]
 [0.0 1.0 0.0 34.0 49000.0]
 [1.0 0.0 0.0 25.0 59000.0]
 [0.0 1.0 0.0 28.0 83000.0]]


In [13]:
print(x_test)

[[1.0 0.0 0.0 35.0 43000.0]
 [0.0 1.0 0.0 41.0 67000.0]]


In [14]:
print(y_train)

[1 0 1 1 1 0 1 0]


In [15]:
print(y_test)

[0 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 0.2528608687120868 0.863077607410918]
 [1.0 0.0 0.0 -0.15171652122725207 -0.1929232298918529]
 [0.0 1.0 0.0 1.668881733499773 -0.05076927102417227]
 [0.0 0.0 1.0 -1.1631599960755992 0.954462295254427]
 [0.0 0.0 1.0 1.0620156485907646 -1.0560008373027716]
 [0.0 1.0 0.0 0.45514956368175624 -1.5129242765203168]
 [1.0 0.0 0.0 -1.3654486910452688 -0.5990773980852264]
 [0.0 1.0 0.0 -0.7585826061362604 1.5941551101589901]]


In [18]:
print(x_test)

[[1.0 0.0 0.0 0.6574382586514257 -2.061232403581371]
 [0.0 1.0 0.0 1.8711704284694424 0.13200010466284579]]
